[versions]
minestom = "2025.07.17-1.21.8"
tinylog = "2.7.0"
gson = "2.12.1"
junit = "5.10.0"
mockito = "5.16.0"
mockito-kotlin = "5.4.0"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
tinylog-api = { group = "org.tinylog", name = "tinylog-api", version.ref = "tinylog" }
tinylog-impl = { group = "org.tinylog", name = "tinylog-impl", version.ref = "tinylog" }
tinylog-slf4j = { group = "org.tinylog", name = "slf4j-tinylog", version.ref = "tinylog" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
